const projects = [
  {
    name: "Anime-Database",
    html_url: "https://github.com/JAZSI/Anime-Database",
    id: 610924224,
    description: "For finding Anime data (Not an anime streaming website)",
    forks_count: 0,
    stargazers_count: 0,
    language: "SCSS",
    image: "/projects/Anime-Database.png",
  },
  {
    name: "ASCII-Art-Converter",
    html_url: "https://github.com/JAZSI/ASCII-Art-Converter",
    id: 581235181,
    description: "Image to Ascii art converter",
    forks_count: 0,
    stargazers_count: 0,
    language: "JavaScript",
    image: "/projects/ASCII-Art-Converter.png",
  },
  {
    name: "Discord-AutoReddit",
    html_url: "https://github.com/JAZSI/Discord-AutoReddit",
    id: 609546924,
    description:
      "Automate posting content from various subreddits to Discord using webhooks",
    forks_count: 0,
    stargazers_count: 0,
    language: "JavaScript",
    image: "/projects/Discord-AutoReddit.png",
  },
  {
    name: "Discord-v14-template",
    html_url: "https://github.com/JAZSI/Discord-v14-template",
    id: 581253762,
    description: "Simple Discord.js v14 bot template",
    forks_count: 0,
    stargazers_count: 0,
    language: "JavaScript",
    image: "/projects/Discord-v14-template.png",
  },
  {
    name: "Ei",
    html_url: "https://github.com/JAZSI/Ei",
    id: 618829563,
    description:
      "Ei is a versatile and fun anime-themed discord bot that can enhance any server's anime experience.",
    forks_count: 0,
    stargazers_count: 0,
    language: "JavaScript",
    image: "/projects/Ei.png",
  },
  {
    name: "Elysia-Bot-Website",
    html_url: "https://github.com/JAZSI/Elysia-Bot-Website",
    id: 599529176,
    description: "A website for a discord bot",
    forks_count: 0,
    stargazers_count: 0,
    language: "HTML",
    image: "/projects/Elysia-Bot-Website.png",
  },
  {
    name: "Elysia-Discord-Chatbot",
    html_url: "https://github.com/JAZSI/Elysia-Discord-Chatbot",
    id: 585152897,
    description:
      "This chatbot is built using the Discord.js library and DialoGPT-Elysia",
    forks_count: 3,
    stargazers_count: 9,
    language: "JavaScript",
    image: "/projects/Elysia-Discord-Chatbot.png",
  },
  {
    name: "Hiragana-Quiz",
    html_url: "https://github.com/JAZSI/Hiragana-Quiz",
    id: 613029876,
    description:
      "A  simple web application that helps users practice their knowledge of the Hiragana writing system in Japanese.",
    forks_count: 0,
    stargazers_count: 0,
    language: "JavaScript",
    image: "/projects/Hiragana-Quiz.png",
  },
  {
    name: "JAZSI",
    html_url: "https://github.com/JAZSI/JAZSI",
    id: 599478838,
    description: "My Github profile README",
    forks_count: 0,
    stargazers_count: 0,
    language: null,
    image: "/projects/JAZSI.png",
  },
  {
    name: "jazsi.github.io",
    html_url: "https://github.com/JAZSI/jazsi.github.io",
    id: 598640007,
    description: "https://jazsi.github.io/",
    forks_count: 0,
    stargazers_count: 0,
    language: "HTML",
    image: "/projects/jazsi.github.io.png",
  },
  {
    name: "OwOfier",
    html_url: "https://github.com/JAZSI/OwOfier",
    id: 589002771,
    description: "OwOify texts",
    forks_count: 0,
    stargazers_count: 0,
    language: "JavaScript",
    image: "/projects/OwOfier.png",
  },
  {
    name: "Portfolio",
    html_url: "https://github.com/JAZSI/Portfolio",
    id: 601724650,
    description: "✨My portfolio website using React.js",
    forks_count: 0,
    stargazers_count: 0,
    language: "JavaScript",
    image: "/projects/Portfolio.png",
  },
  {
    name: "Simple-Todo-List",
    html_url: "https://github.com/JAZSI/Simple-Todo-List",
    id: 613962806,
    description: "A simple todo list app using Vue",
    forks_count: 0,
    stargazers_count: 0,
    language: "Vue",
    image: "/projects/Simple-Todo-List.png",
  },
  {
    name: "Wallpaper-Changer",
    html_url: "https://github.com/JAZSI/Wallpaper-Changer",
    id: 590966030,
    description: "Automatically change wallpapers in windows",
    forks_count: 0,
    stargazers_count: 0,
    language: "Python",
    image: "/projects/Wallpaper-Changer.png",
  },
  {
    id: 1,
    name: "DialoGPT-Elysia",
    description:
      "A fine-tuned version of the DialoGPT-medium model trained on the dialogues of Elysia from the game Honkai Impact.",
    html_url: "https://huggingface.co/Jaszii/DialoGPT-Elysia",
    forks_count: 0,
    stargazers_count: 0,
    language: "NLP Model",
    image: "/projects/DialoGPT-Elysia.png",
  },
  {
    id: 2,
    name: "Aqueous",
    description:
      "Aqueous is a side-scrolling platformer game where players control a protagonist named Aqueous.",
    html_url: "https://jaszi.itch.io/aqueous",
    forks_count: 0,
    stargazers_count: 0,
    language: "HTML",
    image: "/projects/Aqueous.png",
  },
];

export default projects;
