/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 MiniRoom.gltf
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function MiniRoom(props) {
  const { nodes, materials } = useGLTF("/MiniRoom.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group
            position={[546.69, 122.67, -568.11]}
            rotation={[-0.01, 0.08, -1.57]}
            scale={[0.74, 1.35, 1.23]}
          >
            <mesh
              geometry={nodes.Cube_4001.geometry}
              material={materials.glow_white}
              position={[-0.32, 0.86, 0.42]}
              scale={[0.99, 1.01, 1]}
            />
            <mesh
              geometry={nodes.Cube_4002.geometry}
              material={materials.dark_pink}
              position={[-16.68, -0.27, 9.75]}
              scale={[0.99, 1.01, 1]}
            />
            <mesh
              geometry={nodes.Rectangle.geometry}
              material={materials.white}
              position={[-22.7, 32.77, 1.79]}
              rotation={[0, -1.57, 0]}
            />
          </group>
          <group
            position={[648.15, -183.48, -609.72]}
            rotation={[0, -0.26, 0]}
            scale={2.34}
          >
            <mesh
              geometry={nodes.Cube003.geometry}
              material={materials.dark_pink}
              position={[-0.69, -0.53, -1.41]}
              scale={0.78}
            />
            <mesh
              geometry={nodes.Rectangle_2003.geometry}
              material={materials.dark_pink}
              position={[-10.34, -26.88, 57.12]}
            />
          </group>
          <group position={[-177.84, -318.39, 98.4]}>
            <mesh
              geometry={nodes.Ellipse_2002.geometry}
              material={materials.light_blue_purple}
              position={[0, 7.39, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.09, 1.09, 1.66]}
            />
            <mesh
              geometry={nodes.Ellipse003.geometry}
              material={materials.desk}
              position={[0, -7.39, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.09, 1.09, 1.66]}
            />
          </group>
          <group position={[104.84, -148.21, -3.92]} rotation={[0, 0.62, 0]}>
            <mesh
              geometry={nodes.Cube_2001.geometry}
              material={materials.mid_pink}
              position={[-71.76, -13.2, -67.54]}
              rotation={[0.09, 0, -1.66]}
              scale={[0.98, 1, 1]}
            />
            <mesh
              geometry={nodes.Cube_3.geometry}
              material={materials.mid_pink}
              position={[70.48, -13.2, -67.54]}
              rotation={[0.09, 0.02, -1.48]}
              scale={[0.98, 1, 1]}
            />
            <mesh
              geometry={nodes.Cube_3001.geometry}
              material={materials.mid_pink}
              position={[70.48, -13.2, 68.88]}
              rotation={[-0.09, -0.02, -1.48]}
              scale={[0.98, 1, 1]}
            />
            <mesh
              geometry={nodes.Cube001.geometry}
              material={materials.mid_pink}
              position={[-71.76, -13.2, 68.88]}
              rotation={[-0.09, 0.01, -1.66]}
              scale={[0.98, 1, 1]}
            />
            <mesh
              geometry={nodes.Cylinder003.geometry}
              material={materials.mid_pink}
              position={[0, 152.2, 0]}
              rotation={[0, -1.57, 0]}
            />
          </group>
          <group position={[-500.03, 513.28, -855.27]} scale={0.62}>
            <mesh
              geometry={nodes.Ellipse_2001.geometry}
              material={materials.glow_white}
              position={[-127.29, 313.59, 4.65]}
              scale={0.98}
            />
            <mesh
              geometry={nodes.Ellipse_3001.geometry}
              material={materials.glow_white}
              position={[-77.52, 313.59, 4.65]}
              scale={0.98}
            />
            <mesh
              geometry={nodes.Ellipse002.geometry}
              material={materials.glow_white}
              position={[-178.65, 313.59, 4.65]}
              scale={0.98}
            />
            <mesh
              geometry={nodes.Rectangle_5002.geometry}
              material={materials.dark_purple}
              position={[0, 0, -13.47]}
            />
            <mesh
              geometry={nodes.Rectangle_6001.geometry}
              material={materials.light_pink}
              position={[-106.76, 173.68, 3.27]}
            />
            <mesh
              geometry={nodes.Rectangle_7.geometry}
              material={materials.light_purple}
              position={[0, -238.94, 4]}
            />
            <mesh
              geometry={nodes.Rectangle_8.geometry}
              material={materials.mid_pink}
              position={[98.23, 173.68, 3.27]}
            />
            <mesh
              geometry={nodes.Rectangle_9.geometry}
              material={materials.mid_pink}
              position={[98.23, -16.4, 3.27]}
            />
            <mesh
              geometry={nodes.Rectangle_9001.geometry}
              material={materials.mid_pink}
              position={[-106.76, -16.4, 3.27]}
            />
          </group>
          <group position={[643.47, 608.8, -737.72]} scale={1.65}>
            <mesh
              geometry={nodes.Cylinder_2.geometry}
              material={materials.light_pink}
              position={[-0.25, -296.91, 0.71]}
            />
            <mesh
              geometry={nodes.Cylinder_3.geometry}
              material={materials.light_pink}
              position={[-0.53, -212.52, 1.57]}
            />
            <mesh
              geometry={nodes.Cylinder_4.geometry}
              material={materials.glow_yellow}
              position={[0.25, -107.09, -0.71]}
              scale={0.85}
            />
            <mesh
              geometry={nodes.Cylinder_5.geometry}
              material={materials.lambert1}
              position={[-0.16, -149.66, -0.71]}
              scale={0.85}
            />
            <mesh
              geometry={nodes.Cylinder_6.geometry}
              material={materials.glow_yellow}
              position={[-0.16, -65.35, -0.71]}
              scale={0.85}
            />
          </group>
          <group position={[868.51, 713.95, 442.46]}>
            <mesh
              geometry={nodes.Ellipse.geometry}
              material={materials.light_pink}
              position={[-2.54, 147.53, 1.44]}
              rotation={[0, -1.57, 0]}
              scale={0.59}
            />
            <mesh
              geometry={nodes.Ellipse_2.geometry}
              material={materials.yellow}
              position={[-2.54, 70.36, 1.44]}
              rotation={[0, -1.57, 0]}
              scale={0.59}
            />
            <mesh
              geometry={nodes.Ellipse_3.geometry}
              material={materials.dark_purple}
              position={[-2.54, -7.92, 1.44]}
              rotation={[0, -1.57, 0]}
              scale={0.59}
            />
            <mesh
              geometry={nodes.Rectangle_5.geometry}
              material={materials.mid_pink}
              position={[9.48, -26, 0]}
              rotation={[0, -1.57, 0]}
            />
          </group>
          <group position={[578.34, 229.18, -175.74]} rotation={[0, -1.57, 0]}>
            <group position={[-13.7, -104.33, 11.98]}>
              <group
                position={[-92.38, -0.21, -86.27]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.21, 0.11, 0.21]}
              >
                <mesh
                  geometry={nodes.Mesh_11001.geometry}
                  material={materials.light_pink}
                  position={[134, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_11002.geometry}
                  material={materials.light_pink}
                  position={[268, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_11003.geometry}
                  material={materials.light_pink}
                  position={[402, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_11004.geometry}
                  material={materials.light_pink}
                  position={[536, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_11005.geometry}
                  material={materials.light_pink}
                  position={[670, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_11006.geometry}
                  material={materials.light_pink}
                  position={[804, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_11007.geometry}
                  material={materials.light_pink}
                  position={[938, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_11008.geometry}
                  material={materials.light_pink}
                  position={[1072, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_11009.geometry}
                  material={materials.light_pink}
                  position={[1206, 0, 0]}
                />
              </group>
              <group
                position={[-140.42, -0.21, -11.16]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.21}
              >
                <mesh
                  geometry={nodes.Mesh_13001.geometry}
                  material={materials.light_pink}
                  position={[134, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_13002.geometry}
                  material={materials.light_pink}
                  position={[268, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_13003.geometry}
                  material={materials.light_pink}
                  position={[402, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_13004.geometry}
                  material={materials.light_pink}
                  position={[536, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_13005.geometry}
                  material={materials.light_pink}
                  position={[670, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_13006.geometry}
                  material={materials.light_pink}
                  position={[804, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_13007.geometry}
                  material={materials.light_pink}
                  position={[938, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_13008.geometry}
                  material={materials.light_pink}
                  position={[1072, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_13009.geometry}
                  material={materials.light_pink}
                  position={[1206, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_13010.geometry}
                  material={materials.light_pink}
                  position={[1340, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_13011.geometry}
                  material={materials.light_pink}
                  position={[1474, 0, 0]}
                />
              </group>
              <group
                position={[-140.42, -0.21, -47.89]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.21}
              >
                <mesh
                  geometry={nodes.Mesh_14.geometry}
                  material={materials.light_pink}
                />
                <mesh
                  geometry={nodes.Mesh_14001.geometry}
                  material={materials.light_pink}
                  position={[134, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_14002.geometry}
                  material={materials.light_pink}
                  position={[268, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_14003.geometry}
                  material={materials.light_pink}
                  position={[402, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_14004.geometry}
                  material={materials.light_pink}
                  position={[536, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_14005.geometry}
                  material={materials.light_pink}
                  position={[670, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_14006.geometry}
                  material={materials.light_pink}
                  position={[804, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_14007.geometry}
                  material={materials.light_pink}
                  position={[938, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_14008.geometry}
                  material={materials.light_pink}
                  position={[1072, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_14009.geometry}
                  material={materials.light_pink}
                  position={[1206, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_14010.geometry}
                  material={materials.light_pink}
                  position={[1340, 0, 0]}
                />
                <mesh
                  geometry={nodes.Mesh_14011.geometry}
                  material={materials.light_pink}
                  position={[1474, 0, 0]}
                />
              </group>
              <mesh
                geometry={nodes.Cube_10.geometry}
                material={materials.light_pink}
                position={[-137.32, 0, 21.11]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.21, 0.16, 0.21]}
              />
              <mesh
                geometry={nodes.Cube_11.geometry}
                material={materials.light_pink}
                position={[5.67, 0, 24.65]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.21, 0.16, 0.21]}
              />
              <mesh
                geometry={nodes.Cube_12.geometry}
                material={materials.light_pink}
                position={[-100.06, 0, 21.11]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.21, 0.16, 0.21]}
              />
              <mesh
                geometry={nodes.Cube_13.geometry}
                material={materials.light_pink}
                position={[105.5, 0, 21.11]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.21, 0.16, 0.21]}
              />
              <mesh
                geometry={nodes.Cube_14.geometry}
                material={materials.light_pink}
                position={[138.63, 0, 21.11]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.21, 0.16, 0.21]}
              />
              <mesh
                geometry={nodes.Cube_15.geometry}
                material={materials.light_pink}
                position={[2.38, 0.65, 67]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.18, 0.14, 0.18]}
              />
              <mesh
                geometry={nodes.Cube_4.geometry}
                material={materials.light_pink}
                position={[-139.99, -0.21, -80.67]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.21}
              />
              <mesh
                geometry={nodes.Cube_5.geometry}
                material={materials.light_pink}
                position={[-92.38, -0.21, -86.27]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.21, 0.11, 0.21]}
              />
              <mesh
                geometry={nodes.Cube_6.geometry}
                material={materials.light_pink}
                position={[-92.38, -0.21, -86.27]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.21, 0.11, 0.21]}
              />
              <mesh
                geometry={nodes.Cube_8.geometry}
                material={materials.light_pink}
                position={[-140.42, -0.21, -11.16]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.21}
              />
            </group>
            <mesh
              geometry={nodes.bottompart.geometry}
              material={materials.metal_light}
              position={[0, -112.25, 0.82]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes.laptopbackscreen.geometry}
              material={materials.metal_light}
              position={[0, 5.25, -107.82]}
            />
            <mesh
              geometry={nodes.screen.geometry}
              material={materials.glow_screen}
              position={[0, 9.53, -99.27]}
              scale={[0.95, 0.95, 0.25]}
            />
          </group>
          <group position={[688.69, 174.4, 215.4]}>
            <mesh
              geometry={nodes.Cube.geometry}
              material={materials.white}
              position={[-10.67, -17.78, -10.37]}
              rotation={[-0.17, -0.04, 0.26]}
            />
            <mesh
              geometry={nodes.Cube_2.geometry}
              material={materials.yellow}
              position={[6.44, -6.48, 8.59]}
              rotation={[0.25, -0.09, -0.25]}
            />
            <mesh
              geometry={nodes.Cylinder002.geometry}
              material={materials.light_pink}
              position={[-3.34, -58.97, 0]}
            />
          </group>
          <group position={[679.37, 709.51, -857.7]} scale={0.52}>
            <mesh
              geometry={nodes.Rectangle_3002.geometry}
              material={materials.light_pink}
              position={[-1.61, 0, -17.53]}
            />
            <mesh
              geometry={nodes.Rectangle001.geometry}
              material={materials.yellow}
              position={[0, 0, 4.27]}
            />
          </group>
          <group
            position={[666.58, 205.46, 370.5]}
            rotation={[0, -0.17, -0.26]}
          >
            <mesh
              geometry={nodes.Rectangle_2002.geometry}
              material={materials.light_blue_purple}
              position={[-9.93, 0, 0]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              geometry={nodes.Rectangle_3003.geometry}
              material={materials.light_pink}
              position={[55.06, -11.51, 7.12]}
              rotation={[Math.PI / 2, -0.87, Math.PI / 2]}
            />
            <mesh
              geometry={nodes.Rectangle002.geometry}
              material={materials.light_pink}
              position={[4.4, 0, 0]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              geometry={nodes.Shape.geometry}
              material={materials.white}
              position={[-12.4, 52.27, -29.37]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              geometry={nodes.Shape_2.geometry}
              material={materials.dark_pink}
              position={[-10.75, 72.86, -24.1]}
              rotation={[0, -1.57, 0]}
            />
            <mesh
              geometry={nodes.Shape_3.geometry}
              material={materials.desk}
              position={[-10.48, -28.6, -16.28]}
              rotation={[0, -1.57, 0]}
            />
          </group>
          <group
            position={[860.65, 554.31, 737.1]}
            rotation={[0, -1.57, 0]}
            scale={0.71}
          >
            <mesh
              geometry={nodes.Ellipse001.geometry}
              material={materials.glow_white}
              position={[-13.53, 63.18, 9.13]}
              scale={1.3}
            />
            <mesh
              geometry={nodes.Rectangle_5001.geometry}
              material={materials.light_pink}
              position={[-38, 0, -17.88]}
            />
            <mesh
              geometry={nodes.Rectangle_6.geometry}
              material={materials.mid_pink}
              position={[-38.58, 0, -1.01]}
              scale={0.92}
            />
            <mesh
              geometry={nodes.Triangle.geometry}
              material={materials.glow_white}
              position={[-100.91, -31.31, 10.86]}
              scale={[1.16, 1.16, 11432067334144]}
            />
            <mesh
              geometry={nodes.Triangle_2.geometry}
              material={materials.glow_white}
              position={[41.47, -49, 11.47]}
              scale={[1.16, 1.16, 11432067334144]}
            />
          </group>
          <group
            position={[478.18, 52.43, 781.08]}
            rotation={[0, 0.4, 0]}
            scale={0.75}
          >
            <mesh
              geometry={nodes.Cube_2002.geometry}
              material={materials.yellow}
              position={[15.33, 90.95, -1.22]}
              rotation={[0, Math.PI / 4, 0]}
            />
            <mesh
              geometry={nodes.Cube_3002.geometry}
              material={materials.yellow}
              position={[-21.33, 13.1, 36.98]}
              rotation={[-3.05, -Math.PI / 4, -3.05]}
              scale={1.05}
            />
            <mesh
              geometry={nodes.Cube_4004.geometry}
              material={materials.yellow}
              position={[37.57, -65.59, -107]}
              rotation={[-0.04, 1.22, -0.22]}
            />
            <mesh
              geometry={nodes.Cube_5002.geometry}
              material={materials.yellow}
              position={[-12.89, -31.14, 51.83]}
              rotation={[-3.11, 1.3, -2.91]}
              scale={1.05}
            />
            <mesh
              geometry={nodes.Cube002.geometry}
              material={materials.yellow}
              position={[17.45, -42.1, 91.53]}
              rotation={[0, -1.22, -0.17]}
            />
            <mesh
              geometry={nodes.Ellipse_3002.geometry}
              material={materials.dark_pink}
              position={[6.87, -137.16, 1.3]}
              rotation={[-Math.PI / 2, 0, -1.98]}
              scale={1.54}
            />
            <mesh
              geometry={nodes.Plant_Base.geometry}
              material={materials.Pink}
              position={[13.95, -371.94, 0.56]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1.67}
            />
          </group>
          <group
            position={[-301.54, -126.47, -647.86]}
            scale={[1.53, 1.5, 1.22]}
          >
            <mesh
              geometry={nodes.back.geometry}
              material={materials.light_pink}
              position={[-126.87, 23.15, -118.33]}
              rotation={[0, -1.57, 0]}
              scale={[1.01, 0.94, 0.98]}
            />
            <mesh
              geometry={nodes.back001.geometry}
              material={materials.light_pink}
              position={[125.68, 23.15, -118.33]}
              rotation={[0, -1.57, 0]}
              scale={[1.26, 0.94, 1]}
            />
            <mesh
              geometry={nodes.bottom.geometry}
              material={materials.metal_light}
              position={[1.04, -69.3, -7.06]}
              scale={[1, 1, 1.26]}
            />
            <mesh
              geometry={nodes.feet.geometry}
              material={materials.metal_light}
              position={[307.34, -100.08, 145.35]}
            />
            <mesh
              geometry={nodes.feet001.geometry}
              material={materials.metal_light}
              position={[307.34, -100.08, -155.48]}
            />
            <mesh
              geometry={nodes.feet002.geometry}
              material={materials.metal_light}
              position={[-317.19, -100.08, 145.35]}
            />
            <mesh
              geometry={nodes.feet003.geometry}
              material={materials.metal_light}
              position={[-317.19, -100.08, -155.48]}
            />
            <mesh
              geometry={nodes.piilow.geometry}
              material={materials.light_pink}
              position={[121.77, -2.28, 49.29]}
              scale={[1, 1, 0.99]}
            />
            <mesh
              geometry={nodes.pilow.geometry}
              material={materials.light_pink}
              position={[-128.1, -2.28, 49.29]}
              scale={[0.93, 1, 1.1]}
            />
            <mesh
              geometry={nodes.side001.geometry}
              material={materials.light_pink}
              position={[-296.74, 29.07, -8.33]}
              scale={[1, 1, 1.26]}
            />
            <mesh
              geometry={nodes.side002.geometry}
              material={materials.light_pink}
              position={[293.02, 29.07, -8.33]}
              scale={[1, 1, 1.26]}
            />
          </group>
          <group position={[618.83, -107.95, -266.73]} scale={0.7}>
            <mesh
              geometry={nodes.Cylinder_2003.geometry}
              material={materials.desk}
              position={[262.37, -38.32, 862.8]}
            />
            <mesh
              geometry={nodes.Cylinder_3001.geometry}
              material={materials.desk}
              position={[262.37, -38.32, -709.39]}
            />
            <mesh
              geometry={nodes.Cylinder_3002.geometry}
              material={materials.desk}
              position={[-249.05, -35.67, -709.39]}
            />
            <mesh
              geometry={nodes.Cylinder004.geometry}
              material={materials.desk}
              position={[-249.05, -38.32, 862.8]}
            />
            <mesh
              geometry={nodes.Rectangle003.geometry}
              material={materials.light_blue_purple}
              position={[0, 230.16, 91.5]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            />
          </group>
          <group
            position={[860.18, 559.18, -103.29]}
            rotation={[0, -1.57, 0]}
            scale={0.66}
          >
            <group position={[381.08, 121.32, 18.33]} scale={1.01}>
              <mesh
                geometry={nodes.Cylinder.geometry}
                material={materials.light_purple}
                position={[-8.64, -133.57, 0.8]}
                rotation={[0, 0, Math.PI / 2]}
                scale={[1, 1.08, 1]}
              />
              <mesh
                geometry={nodes.Cylinder_2001.geometry}
                material={materials.light_purple}
                position={[-11.1, 133.57, 0.8]}
                rotation={[0, 0, -Math.PI / 2]}
                scale={[1, 1.08, 1]}
              />
              <mesh
                geometry={nodes.Cylinder_2002.geometry}
                material={materials.light_purple}
                position={[123.29, 0.97, 0.8]}
                rotation={[0, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Cylinder001.geometry}
                material={materials.light_purple}
                position={[-142.85, -0.97, 0.8]}
              />
              <mesh
                geometry={nodes.Sphere.geometry}
                material={materials.light_purple}
                position={[-141.8, -132.87, 0]}
                rotation={[0, 0, Math.PI / 2]}
              />
              <mesh
                geometry={nodes.Sphere_2.geometry}
                material={materials.light_purple}
                position={[122.25, 132.87, 0]}
                rotation={[0, 0, -Math.PI / 2]}
              />
              <mesh
                geometry={nodes.Sphere_2001.geometry}
                material={materials.light_purple}
                position={[122.59, -132.87, 0]}
                rotation={[0, 0, -Math.PI]}
              />
              <mesh
                geometry={nodes.Sphere001.geometry}
                material={materials.light_purple}
                position={[-142.14, 132.87, 0]}
              />
            </group>
            <group position={[372.71, 159.53, 22.45]} scale={1.52}>
              <mesh
                geometry={nodes.A.geometry}
                material={materials.glow_white}
                position={[-77, -67.5, 0]}
              />
              <mesh
                geometry={nodes.a.geometry}
                material={materials.glow_white}
                position={[3.91, -67.5, 0]}
              />
            </group>
            <mesh
              geometry={nodes.Rectangle_2.geometry}
              material={materials.glow_white}
              position={[410.36, -135.84, 5.68]}
              scale={1.52}
            />
            <mesh
              geometry={nodes.Rectangle_2001.geometry}
              material={materials.light_pink}
              position={[0, 0, -23.62]}
            />
            <mesh
              geometry={nodes.Rectangle_3.geometry}
              material={materials.glow_white}
              position={[369.97, -225.14, 5.68]}
              scale={1.52}
            />
            <mesh
              geometry={nodes.Rectangle_3001.geometry}
              material={materials.dark_purple}
              position={[0, -44, 5.66]}
            />
            <mesh
              geometry={nodes.Rectangle_4.geometry}
              material={materials.glow_white}
              position={[369.97, -315.35, 5.68]}
              scale={1.52}
            />
            <mesh
              geometry={nodes.Rectangle_5003.geometry}
              material={materials.light_purple}
              position={[-180.73, -40.12, 19.4]}
            />
          </group>
          <group position={[129, 617.5, -853.89]}>
            <mesh
              geometry={nodes.Cube_4003.geometry}
              material={materials.dark_pink}
              position={[0.63, 0.94, -10.81]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.Cube_5001.geometry}
              material={materials.dark_pink}
              position={[1.69, 105.58, 0]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.窗户.geometry}
              material={materials.glow_window}
              position={[0, 0, 9.16]}
              rotation={[0, 0, -Math.PI / 2]}
            />
          </group>
          <mesh
            geometry={nodes["book-green"].geometry}
            material={materials.yellow}
            position={[797.82, 181.7, -733.6]}
            rotation={[-Math.PI / 2, -1.4, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes["book-red"].geometry}
            material={materials.dark_pink}
            position={[873.04, 235.86, -716.95]}
            rotation={[0, -1.57, 0]}
          />
          <mesh
            geometry={nodes["book-yellow"].geometry}
            material={materials.light_purple}
            position={[850.55, 201.36, -716.95]}
            rotation={[0, -1.57, 0]}
          />
          <mesh
            geometry={nodes.paper.geometry}
            material={materials.white}
            position={[490.67, 107.27, -605.12]}
            rotation={[-Math.PI / 2, 0, -1.13]}
          />
          <group
            position={[33.17, -323.76, -23.55]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={0.7}
          >
            <mesh
              geometry={nodes.Mesh056.geometry}
              material={materials.floor}
            />
            <mesh
              geometry={nodes.Mesh056_1.geometry}
              material={materials.black}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/MiniRoom.gltf");

export default MiniRoom;
