/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mini_room.gltf
*/

import React, { useRef } from "react";
import { useGLTF, OrthographicCamera } from "@react-three/drei";

function MiniRoom(props) {
  const { nodes, materials } = useGLTF("/mini_room.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-301.54, -126.47, -647.86]} scale={[1.53, 1.5, 1.22]}>
          <mesh
            geometry={nodes.piilow.geometry}
            material={nodes.piilow.material}
            position={[121.77, -2.28, 49.29]}
            scale={[1, 1, 0.99]}
          />
          <mesh
            geometry={nodes.pilow.geometry}
            material={nodes.pilow.material}
            position={[-128.1, -2.28, 49.29]}
            scale={[0.93, 1, 1.1]}
          />
          <mesh
            geometry={nodes.side.geometry}
            material={nodes.side.material}
            position={[296.74, 29.07, -8.33]}
            scale={[1, 1, 1.26]}
          />
          <mesh
            geometry={nodes.side_1.geometry}
            material={nodes.side_1.material}
            position={[-296.74, 29.07, -8.33]}
            scale={[1, 1, 1.26]}
          />
          <mesh
            geometry={nodes.back.geometry}
            material={nodes.back.material}
            position={[-126.87, 23.15, -118.33]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[1.01, 0.94, 0.98]}
          />
          <mesh
            geometry={nodes.back_1.geometry}
            material={nodes.back_1.material}
            position={[125.68, 23.15, -118.33]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[1.26, 0.94, 1]}
          />
          <mesh
            geometry={nodes.bottom.geometry}
            material={nodes.bottom.material}
            position={[1.05, -69.3, -7.06]}
            scale={[1, 1, 1.26]}
          />
          <mesh
            geometry={nodes.feet.geometry}
            material={nodes.feet.material}
            position={[307.34, -100.08, 145.35]}
          />
          <mesh
            geometry={nodes.feet_1.geometry}
            material={nodes.feet_1.material}
            position={[307.34, -100.08, -155.48]}
          />
          <mesh
            geometry={nodes.feet_2.geometry}
            material={nodes.feet_2.material}
            position={[-317.19, -100.08, 145.35]}
          />
          <mesh
            geometry={nodes.feet_3.geometry}
            material={nodes.feet_3.material}
            position={[-317.19, -100.08, -155.48]}
          />
        </group>
        <group
          position={[578.34, 229.18, -175.74]}
          rotation={[0, -Math.PI / 2, 0]}
        >
          <group position={[-13.7, -104.33, 11.98]}>
            <group
              position={[-92.38, -0.21, -86.27]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.21, 0.11, 0.21]}
            >
              <mesh
                geometry={nodes.mesh_11_instance_1.geometry}
                material={nodes.mesh_11_instance_1.material}
              />
              <mesh
                geometry={nodes.mesh_11_instance_2.geometry}
                material={nodes.mesh_11_instance_2.material}
                position={[134, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_11_instance_3.geometry}
                material={nodes.mesh_11_instance_3.material}
                position={[268, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_11_instance_4.geometry}
                material={nodes.mesh_11_instance_4.material}
                position={[402, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_11_instance_5.geometry}
                material={nodes.mesh_11_instance_5.material}
                position={[536, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_11_instance_6.geometry}
                material={nodes.mesh_11_instance_6.material}
                position={[670, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_11_instance_7.geometry}
                material={nodes.mesh_11_instance_7.material}
                position={[804, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_11_instance_8.geometry}
                material={nodes.mesh_11_instance_8.material}
                position={[938, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_11_instance_9.geometry}
                material={nodes.mesh_11_instance_9.material}
                position={[1072, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_11_instance_10.geometry}
                material={nodes.mesh_11_instance_10.material}
                position={[1206, 0, 0]}
              />
            </group>
            <group
              position={[-140.42, -0.21, -11.16]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.21}
            >
              <mesh
                geometry={nodes.mesh_13_instance_1.geometry}
                material={nodes.mesh_13_instance_1.material}
              />
              <mesh
                geometry={nodes.mesh_13_instance_2.geometry}
                material={nodes.mesh_13_instance_2.material}
                position={[134, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_13_instance_3.geometry}
                material={nodes.mesh_13_instance_3.material}
                position={[268, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_13_instance_4.geometry}
                material={nodes.mesh_13_instance_4.material}
                position={[402, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_13_instance_5.geometry}
                material={nodes.mesh_13_instance_5.material}
                position={[536, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_13_instance_6.geometry}
                material={nodes.mesh_13_instance_6.material}
                position={[670, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_13_instance_7.geometry}
                material={nodes.mesh_13_instance_7.material}
                position={[804, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_13_instance_8.geometry}
                material={nodes.mesh_13_instance_8.material}
                position={[938, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_13_instance_9.geometry}
                material={nodes.mesh_13_instance_9.material}
                position={[1072, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_13_instance_10.geometry}
                material={nodes.mesh_13_instance_10.material}
                position={[1206, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_13_instance_11.geometry}
                material={nodes.mesh_13_instance_11.material}
                position={[1340, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_13_instance_12.geometry}
                material={nodes.mesh_13_instance_12.material}
                position={[1474, 0, 0]}
              />
            </group>
            <group
              position={[-140.42, -0.21, -47.89]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.21}
            >
              <mesh
                geometry={nodes.mesh_14_instance_1.geometry}
                material={nodes.mesh_14_instance_1.material}
              />
              <mesh
                geometry={nodes.mesh_14_instance_2.geometry}
                material={nodes.mesh_14_instance_2.material}
                position={[134, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_14_instance_3.geometry}
                material={nodes.mesh_14_instance_3.material}
                position={[268, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_14_instance_4.geometry}
                material={nodes.mesh_14_instance_4.material}
                position={[402, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_14_instance_5.geometry}
                material={nodes.mesh_14_instance_5.material}
                position={[536, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_14_instance_6.geometry}
                material={nodes.mesh_14_instance_6.material}
                position={[670, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_14_instance_7.geometry}
                material={nodes.mesh_14_instance_7.material}
                position={[804, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_14_instance_8.geometry}
                material={nodes.mesh_14_instance_8.material}
                position={[938, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_14_instance_9.geometry}
                material={nodes.mesh_14_instance_9.material}
                position={[1072, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_14_instance_10.geometry}
                material={nodes.mesh_14_instance_10.material}
                position={[1206, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_14_instance_11.geometry}
                material={nodes.mesh_14_instance_11.material}
                position={[1340, 0, 0]}
              />
              <mesh
                geometry={nodes.mesh_14_instance_12.geometry}
                material={nodes.mesh_14_instance_12.material}
                position={[1474, 0, 0]}
              />
            </group>
            <mesh
              geometry={nodes.Cube_6_1.geometry}
              material={nodes.Cube_6_1.material}
              position={[-92.38, -0.21, -86.27]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.21, 0.11, 0.21]}
            />
            <mesh
              geometry={nodes.Cube_5_2.geometry}
              material={nodes.Cube_5_2.material}
              position={[-92.38, -0.21, -86.27]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.21, 0.11, 0.21]}
            />
            <mesh
              geometry={nodes.Cube_8.geometry}
              material={nodes.Cube_8.material}
              position={[-140.42, -0.21, -11.16]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.21}
            />
            <mesh
              geometry={nodes.Cube_7_1.geometry}
              material={nodes.Cube_7_1.material}
              position={[-140.42, -0.21, -47.89]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.21}
            />
            <mesh
              geometry={nodes.Cube_15.geometry}
              material={nodes.Cube_15.material}
              position={[2.38, 0.65, 67]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.18, 0.14, 0.18]}
            />
            <mesh
              geometry={nodes.Cube_11.geometry}
              material={nodes.Cube_11.material}
              position={[5.67, 0, 24.65]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.21, 0.16, 0.21]}
            />
            <mesh
              geometry={nodes.Cube_14.geometry}
              material={nodes.Cube_14.material}
              position={[138.63, 0, 21.11]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.21, 0.16, 0.21]}
            />
            <mesh
              geometry={nodes.Cube_13.geometry}
              material={nodes.Cube_13.material}
              position={[105.5, 0, 21.11]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.21, 0.16, 0.21]}
            />
            <mesh
              geometry={nodes.Cube_12.geometry}
              material={nodes.Cube_12.material}
              position={[-100.06, 0, 21.11]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.21, 0.16, 0.21]}
            />
            <mesh
              geometry={nodes.Cube_10.geometry}
              material={nodes.Cube_10.material}
              position={[-137.32, 0, 21.11]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.21, 0.16, 0.21]}
            />
            <mesh
              geometry={nodes.Cube_4_4.geometry}
              material={nodes.Cube_4_4.material}
              position={[-139.99, -0.21, -80.67]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.21}
            />
          </group>
          <mesh
            geometry={nodes.bottompart.geometry}
            material={nodes.bottompart.material}
            position={[0, -112.25, 0.82]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.screen.geometry}
            material={nodes.screen.material}
            position={[0, 9.53, -99.27]}
            scale={[0.95, 0.95, 0.25]}
          />
          <mesh
            geometry={nodes.laptopbackscreen.geometry}
            material={nodes.laptopbackscreen.material}
            position={[0, 5.25, -107.82]}
          />
        </group>
        <group
          position={[546.69, 122.67, -568.11]}
          rotation={[-0.01, 0.08, -1.57]}
          scale={[0.74, 1.35, 1.23]}
        >
          <mesh
            geometry={nodes.Rectangle.geometry}
            material={nodes.Rectangle.material}
            position={[-22.7, 32.77, 1.79]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Cube_4.geometry}
            material={nodes.Cube_4.material}
            position={[-0.32, 0.86, 0.42]}
            scale={[0.99, 1.01, 1]}
          />
          <mesh
            geometry={nodes.Cube_4_1.geometry}
            material={nodes.Cube_4_1.material}
            position={[-16.68, -0.27, 9.75]}
            scale={[0.99, 1.01, 1]}
          />
        </group>
        <group position={[643.47, 608.8, -737.72]} scale={1.65}>
          <mesh
            geometry={nodes.Cylinder_4.geometry}
            material={nodes.Cylinder_4.material}
            position={[0.25, -107.09, -0.71]}
            scale={0.85}
          />
          <mesh
            geometry={nodes.Cylinder_6.geometry}
            material={nodes.Cylinder_6.material}
            position={[-0.16, -65.35, -0.71]}
            scale={0.85}
          />
          <mesh
            geometry={nodes.Cylinder_5.geometry}
            material={nodes.Cylinder_5.material}
            position={[-0.16, -149.66, -0.71]}
            scale={0.85}
          />
          <mesh
            geometry={nodes.Cylinder_3.geometry}
            material={nodes.Cylinder_3.material}
            position={[-0.53, -212.52, 1.57]}
          />
          <mesh
            geometry={nodes.Cylinder_2.geometry}
            material={nodes.Cylinder_2.material}
            position={[-0.25, -296.92, 0.71]}
          />
        </group>
        <group position={[868.51, 713.95, 442.46]}>
          <mesh
            geometry={nodes.Ellipse_3.geometry}
            material={nodes.Ellipse_3.material}
            position={[-2.54, -7.92, 1.44]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.59}
          />
          <mesh
            geometry={nodes.Ellipse_2.geometry}
            material={nodes.Ellipse_2.material}
            position={[-2.54, 70.36, 1.44]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.59}
          />
          <mesh
            geometry={nodes.Ellipse.geometry}
            material={nodes.Ellipse.material}
            position={[-2.54, 147.53, 1.44]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.59}
          />
          <mesh
            geometry={nodes.Rectangle_5.geometry}
            material={nodes.Rectangle_5.material}
            position={[9.48, -26, 0]}
            rotation={[0, -Math.PI / 2, 0]}
          />
        </group>
        <group
          position={[860.65, 554.31, 737.1]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.71}
        >
          <mesh
            geometry={nodes.Triangle_2.geometry}
            material={nodes.Triangle_2.material}
            position={[41.47, -49, 11.47]}
            scale={[1.16, 1.16, 11432065741406.77]}
          />
          <mesh
            geometry={nodes.Triangle.geometry}
            material={nodes.Triangle.material}
            position={[-100.91, -31.31, 10.86]}
            scale={[1.16, 1.16, 11432065741406.77]}
          />
          <mesh
            geometry={nodes.Ellipse_1.geometry}
            material={nodes.Ellipse_1.material}
            position={[-13.53, 63.18, 9.13]}
            scale={1.3}
          />
          <mesh
            geometry={nodes.Rectangle_6.geometry}
            material={nodes.Rectangle_6.material}
            position={[-38.58, 0, -1.01]}
            scale={0.92}
          />
          <mesh
            geometry={nodes.Rectangle_5_1.geometry}
            material={nodes.Rectangle_5_1.material}
            position={[-38, 0, -17.88]}
          />
        </group>
        <group position={[-500.03, 513.28, -855.28]} scale={0.62}>
          <mesh
            geometry={nodes.Ellipse_3_1.geometry}
            material={nodes.Ellipse_3_1.material}
            position={[-77.52, 313.59, 4.65]}
            scale={0.98}
          />
          <mesh
            geometry={nodes.Ellipse_2_1.geometry}
            material={nodes.Ellipse_2_1.material}
            position={[-127.29, 313.59, 4.65]}
            scale={0.98}
          />
          <mesh
            geometry={nodes.Ellipse_4.geometry}
            material={nodes.Ellipse_4.material}
            position={[-178.65, 313.59, 4.65]}
            scale={0.98}
          />
          <mesh
            geometry={nodes.Rectangle_7.geometry}
            material={nodes.Rectangle_7.material}
            position={[0, -238.94, 4]}
          />
          <mesh
            geometry={nodes.Rectangle_9.geometry}
            material={nodes.Rectangle_9.material}
            position={[98.23, -16.4, 3.27]}
          />
          <mesh
            geometry={nodes.Rectangle_8.geometry}
            material={nodes.Rectangle_8.material}
            position={[98.23, 173.68, 3.27]}
          />
          <mesh
            geometry={nodes.Rectangle_9_1.geometry}
            material={nodes.Rectangle_9_1.material}
            position={[-106.76, -16.4, 3.27]}
          />
          <mesh
            geometry={nodes.Rectangle_6_1.geometry}
            material={nodes.Rectangle_6_1.material}
            position={[-106.76, 173.68, 3.27]}
          />
          <mesh
            geometry={nodes.Rectangle_5_2.geometry}
            material={nodes.Rectangle_5_2.material}
            position={[0, 0, -13.47]}
          />
        </group>
        <group
          position={[860.18, 559.18, -103.29]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.66}
        >
          <group position={[381.08, 121.32, 18.33]} scale={1.01}>
            <mesh
              geometry={nodes.Cylinder_2_2.geometry}
              material={nodes.Cylinder_2_2.material}
              position={[-11.1, 133.57, 0.8]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[1, 1.08, 1]}
            />
            <mesh
              geometry={nodes.Cylinder_8.geometry}
              material={nodes.Cylinder_8.material}
              position={[-8.64, -133.57, 0.8]}
              rotation={[0, 0, Math.PI / 2]}
              scale={[1, 1.08, 1]}
            />
            <mesh
              geometry={nodes.Sphere_2.geometry}
              material={nodes.Sphere_2.material}
              position={[122.25, 132.87, 0]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              geometry={nodes.Sphere_2_1.geometry}
              material={nodes.Sphere_2_1.material}
              position={[122.59, -132.87, 0]}
              rotation={[0, 0, Math.PI]}
            />
            <mesh
              geometry={nodes.Sphere.geometry}
              material={nodes.Sphere.material}
              position={[-141.8, -132.87, 0]}
              rotation={[0, 0, Math.PI / 2]}
            />
            <mesh
              geometry={nodes.Cylinder_2_3.geometry}
              material={nodes.Cylinder_2_3.material}
              position={[123.29, 0.97, 0.8]}
              rotation={[0, 0, Math.PI]}
            />
            <mesh
              geometry={nodes.Cylinder_9.geometry}
              material={nodes.Cylinder_9.material}
              position={[-142.85, -0.97, 0.8]}
            />
            <mesh
              geometry={nodes.Sphere_1.geometry}
              material={nodes.Sphere_1.material}
              position={[-142.14, 132.87, 0]}
            />
          </group>
          <group position={[372.71, 159.53, 22.45]} scale={1.52}>
            <mesh
              geometry={nodes.A.geometry}
              material={nodes.A.material}
              position={[-77, -67.5, 0]}
            />
            <mesh
              geometry={nodes.a.geometry}
              material={nodes.a.material}
              position={[3.91, -67.5, 0]}
            />
          </group>
          <mesh
            geometry={nodes.Rectangle_4.geometry}
            material={nodes.Rectangle_4.material}
            position={[369.97, -315.35, 5.68]}
            scale={1.52}
          />
          <mesh
            geometry={nodes.Rectangle_3.geometry}
            material={nodes.Rectangle_3.material}
            position={[369.97, -225.14, 5.68]}
            scale={1.52}
          />
          <mesh
            geometry={nodes.Rectangle_2.geometry}
            material={nodes.Rectangle_2.material}
            position={[410.36, -135.84, 5.68]}
            scale={1.52}
          />
          <mesh
            geometry={nodes.Rectangle_5_3.geometry}
            material={nodes.Rectangle_5_3.material}
            position={[-180.73, -40.12, 19.4]}
          />
          <mesh
            geometry={nodes.Rectangle_3_1.geometry}
            material={nodes.Rectangle_3_1.material}
            position={[0, -44, 5.66]}
          />
          <mesh
            geometry={nodes.Rectangle_2_1.geometry}
            material={nodes.Rectangle_2_1.material}
            position={[0, 0, -23.62]}
          />
        </group>
        <group position={[688.69, 174.4, 215.4]}>
          <mesh
            geometry={nodes.Cube_2.geometry}
            material={nodes.Cube_2.material}
            position={[6.44, -6.48, 8.59]}
            rotation={[0.25, -0.09, -0.25]}
          />
          <mesh
            geometry={nodes.Cube.geometry}
            material={nodes.Cube.material}
            position={[-10.67, -17.78, -10.37]}
            rotation={[-0.17, -0.04, 0.26]}
          />
          <mesh
            geometry={nodes.Cylinder.geometry}
            material={nodes.Cylinder.material}
            position={[-3.34, -58.97, 0]}
          />
        </group>
        <group position={[679.37, 709.51, -857.7]} scale={0.52}>
          <mesh
            geometry={nodes.Rectangle_3_2.geometry}
            material={nodes.Rectangle_3_2.material}
            position={[-1.61, 0, -17.53]}
          />
          <mesh
            geometry={nodes.Rectangle_1.geometry}
            material={nodes.Rectangle_1.material}
            position={[0, 0, 4.27]}
          />
        </group>
        <group position={[666.58, 205.46, 370.5]} rotation={[0, -0.17, -0.26]}>
          <mesh
            geometry={nodes.Shape_3.geometry}
            material={nodes.Shape_3.material}
            position={[-10.48, -28.6, -16.28]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Shape_2.geometry}
            material={nodes.Shape_2.material}
            position={[-10.75, 72.86, -24.1]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Shape.geometry}
            material={nodes.Shape.material}
            position={[-12.4, 52.27, -29.37]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Rectangle_2_2.geometry}
            material={nodes.Rectangle_2_2.material}
            position={[-9.93, 0, 0]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            geometry={nodes.Rectangle_3_3.geometry}
            material={nodes.Rectangle_3_3.material}
            position={[55.06, -11.51, 7.12]}
            rotation={[Math.PI / 2, -0.87, Math.PI / 2]}
          />
          <mesh
            geometry={nodes.Rectangle_10.geometry}
            material={nodes.Rectangle_10.material}
            position={[4.4, 0, 0]}
            rotation={[0, -Math.PI / 2, 0]}
          />
        </group>
        <group position={[129, 617.5, -853.89]}>
          <mesh
            geometry={nodes.Cube_4_2.geometry}
            material={nodes.Cube_4_2.material}
            position={[0.63, 0.94, -10.81]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.Cube_5.geometry}
            material={nodes.Cube_5.material}
            position={[1.69, 105.58, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            geometry={nodes.窗户.geometry}
            material={nodes.窗户.material}
            position={[0, 0, 9.16]}
            rotation={[0, 0, -Math.PI / 2]}
          />
        </group>
        <group position={[104.84, -148.21, -3.92]} rotation={[0, 0.62, 0]}>
          <mesh
            geometry={nodes.Cube_3.geometry}
            material={nodes.Cube_3.material}
            position={[70.48, -13.2, -67.54]}
            rotation={[0.09, 0.02, -1.48]}
            scale={[0.98, 1, 1]}
          />
          <mesh
            geometry={nodes.Cube_3_1.geometry}
            material={nodes.Cube_3_1.material}
            position={[70.48, -13.2, 68.88]}
            rotation={[-0.09, -0.02, -1.48]}
            scale={[0.98, 1, 1]}
          />
          <mesh
            geometry={nodes.Cube_2_1.geometry}
            material={nodes.Cube_2_1.material}
            position={[-71.76, -13.2, -67.54]}
            rotation={[0.09, 0, -1.66]}
            scale={[0.98, 1, 1]}
          />
          <mesh
            geometry={nodes.Cube_1.geometry}
            material={nodes.Cube_1.material}
            position={[-71.76, -13.2, 68.88]}
            rotation={[-0.09, 0.01, -1.66]}
            scale={[0.98, 1, 1]}
          />
          <mesh
            geometry={nodes.Cylinder_1.geometry}
            material={nodes.Cylinder_1.material}
            position={[0, 152.2, 0]}
            rotation={[0, -Math.PI / 2, 0]}
          />
        </group>
        <group
          position={[478.18, 52.43, 781.08]}
          rotation={[0, 0.4, 0]}
          scale={0.75}
        >
          <mesh
            geometry={nodes.Cube_2_2.geometry}
            material={nodes.Cube_2_2.material}
            position={[15.33, 90.95, -1.22]}
            rotation={[0, Math.PI / 4, 0]}
          />
          <mesh
            geometry={nodes.Cube_3_2.geometry}
            material={nodes.Cube_3_2.material}
            position={[-21.33, 13.1, 36.98]}
            rotation={[-3.05, -Math.PI / 4, -3.05]}
            scale={1.05}
          />
          <mesh
            geometry={nodes.Cube_4_3.geometry}
            material={nodes.Cube_4_3.material}
            position={[37.57, -65.59, -107]}
            rotation={[-0.04, 1.22, -0.22]}
          />
          <mesh
            geometry={nodes.Cube_5_1.geometry}
            material={nodes.Cube_5_1.material}
            position={[-12.89, -31.14, 51.83]}
            rotation={[-3.11, 1.3, -2.91]}
            scale={1.05}
          />
          <mesh
            geometry={nodes.Cube_6.geometry}
            material={nodes.Cube_6.material}
            position={[17.45, -42.1, 91.53]}
            rotation={[0, -1.22, -0.17]}
          />
          <mesh
            geometry={nodes.Ellipse_3_2.geometry}
            material={nodes.Ellipse_3_2.material}
            position={[6.87, -137.16, 1.3]}
            rotation={[-Math.PI / 2, 0, -1.98]}
            scale={1.54}
          />
          <mesh
            geometry={nodes.Plant_Base.geometry}
            material={nodes.Plant_Base.material}
            position={[13.95, -371.94, 0.56]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.67}
          />
        </group>
        <group
          position={[648.15, -183.48, -609.72]}
          rotation={[0, -0.26, 0]}
          scale={2.34}
        >
          <mesh
            geometry={nodes.Rectangle_2_3.geometry}
            material={nodes.Rectangle_2_3.material}
            position={[-10.34, -26.88, 57.12]}
          />
          <mesh
            geometry={nodes.Cube_7.geometry}
            material={nodes.Cube_7.material}
            position={[-0.69, -0.53, -1.41]}
            scale={0.78}
          />
        </group>
        <group position={[618.83, -107.95, -266.73]} scale={0.7}>
          <mesh
            geometry={nodes.Cylinder_3_1.geometry}
            material={nodes.Cylinder_3_1.material}
            position={[262.37, -38.32, -709.39]}
          />
          <mesh
            geometry={nodes.Cylinder_2_1.geometry}
            material={nodes.Cylinder_2_1.material}
            position={[262.37, -38.32, 862.8]}
          />
          <mesh
            geometry={nodes.Cylinder_3_2.geometry}
            material={nodes.Cylinder_3_2.material}
            position={[-249.05, -35.67, -709.39]}
          />
          <mesh
            geometry={nodes.Cylinder_7.geometry}
            material={nodes.Cylinder_7.material}
            position={[-249.05, -38.32, 862.8]}
          />
          <mesh
            geometry={nodes.Rectangle_11.geometry}
            material={nodes.Rectangle_11.material}
            position={[0, 230.16, 91.5]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
        </group>
        <group position={[-177.84, -318.39, 98.4]}>
          <mesh
            geometry={nodes.Ellipse_2_2.geometry}
            material={nodes.Ellipse_2_2.material}
            position={[0, 7.39, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.09, 1.09, 1.66]}
          />
          <mesh
            geometry={nodes.Ellipse_5.geometry}
            material={nodes.Ellipse_5.material}
            position={[0, -7.39, 0]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[1.09, 1.09, 1.66]}
          />
        </group>
        <directionalLight
          intensity={0.7}
          decay={2}
          rotation={[1.2, 0.51, -1.38]}
        />
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={0}
          position={[-3662.89, 2379.99, 3678.25]}
          rotation={[-0.54, -0.71, -0.37]}
        />
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={0}
          position={[-3695.54, 2809.18, 3596.53]}
          rotation={[-0.53, -0.73, -0.37]}
        />
        <mesh
          geometry={nodes.Walls.geometry}
          material={nodes.Walls.material}
          position={[33.17, -323.76, -23.55]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.7}
        />
        <mesh
          geometry={nodes["book-green"].geometry}
          material={nodes["book-green"].material}
          position={[797.82, 181.7, -733.6]}
          rotation={[-Math.PI / 2, -1.4, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes["book-red"].geometry}
          material={nodes["book-red"].material}
          position={[873.04, 235.86, -716.95]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes["book-yellow"].geometry}
          material={nodes["book-yellow"].material}
          position={[850.55, 201.36, -716.95]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          geometry={nodes.paper.geometry}
          material={nodes.paper.material}
          position={[490.67, 107.27, -605.12]}
          rotation={[-Math.PI / 2, 0, -1.13]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/mini_room.gltf");

export default MiniRoom;
