/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Earth.glb
3D model from https://solarsystem.nasa.gov/resources/2393/earth-3d-model/
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function Earth(props) {
  const { nodes, materials } = useGLTF("/Earth.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Default OBJ"]}
      />
    </group>
  );
}

useGLTF.preload("/Earth.gltf");

export default Earth;
